gigsyncevents/gigsyncevents/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls')),
]

gigsyncevents/web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'

urlpatterns = [
    url(r'^populate/$', views.populate, name='populate'),
    url(r'^add_event/(?P<fb_id>[0-9]+)/$', views.add_event, name='add_event'),
    url(r'^$', views.home, name='home'),
    url(r'^filter', views.filter, name='filter'),
    url(r'^event/(?P<event_id>[0-9]+)/$', views.event, name='event'),
    url(r'^all/$', views.all, name='all'),
    url(r'^today/$', views.today, name='today'),
    url(r'^today/filter', views.today_filter, name='today_filter'),
    url(r'^tomorrow/$', views.tomorrow, name='tomorrow'),
    url(r'^tomorrow/filter', views.tomorrow_filter, name='tomorrow_filter'),
    url(r'^date/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.date, name='date'),
    url(r'^date/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/filter', views.date_filter, name='date_filter'),
    url(r'^delete/', views.delete, name='delete'),
    url(r'^about/', views.about, name='about'),
    url(r'^howto/', views.howto, name='howto'),
]

gigsyncevents/web/templates/web/about.html
{% extends "web/base.html" %}
{% block title %}GigSync Events|About{% endblock %}

{% block nav %}
<li class="nav-item m-sm-2">
        <a class="nav-link" href="{% url 'web:home' %}">Home</a>
    </li>
    <li class="nav-item active m-sm-2">
        <a class="nav-link" href="#">About</a>
    </li>
    <li class="nav-item  m-sm-2">
        <a class="nav-link" href="{% url 'web:howto' %}">HowTo</a>
    </li>
    <li class="nav-item">
        <a href="http://www.gigsync.in/#signup-tab"><button class="btn btn-outline-gspurple my-2" type="submit">Register</button></a>
    </li>
{% endblock %}

{% block main %}
<div class="container my-5">
    <div class="d-flex flex-column justify-content-center">
        <p class="lead text-center">About</p>
        <p class="text-center">About text</p>
    </div>
</div>
{% endblock %}

gigsyncevents/web/templates/web/all.html
<!DOCTYPE html>
    <body>
        <h1>All Events</h1>
        <div>
            {% for event in all_events|dictsort:"start_date" %}
                <div>
                    <p>event_id: {{ event.event_id }}</p>
                    <p>name: {{ event.name }}</p>
                    <p>description: {{ event.description }}</p>
                    <p>start_date: {{ event.start_date }}</p>
                    <p>start_time: {{ event.start_time }}</p>
                    <p>end_date: {{ event.end_date }}</p>
                    <p>end_time: {{ event.end_time }}</p>
                    <p>venue: {{ event.venue }}</p>
                    <p>city: {{ event.city }}</p>
                    <p>cover_link: {{ event.cover_link }}</p>
                    <p>place_id: {{ event.place_id }}</p>
                    <br>
                </div>
            {% endfor %}
        </div>
    </body>
</html>

gigsyncevents/web/templates/web/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://fonts.googleapis.com/css?family=Montserrat|Raleway" rel="stylesheet">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
     crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.standalone.css" />
	<!--<link rel="stylesheet" href="css/style.css" type="text/stylesheet">-->
    <link rel="stylesheet" href="{% static 'css/common.css' %}" type="text/css">
    <script def src="{% static 'js/fontawesome-all.js' %}"></script>
	<title>{% block title %} 
			GigSync Events 
			{% endblock %}
	</title>
</head>

<body>
	<!--NAVBAR-->
	<header class="navbar navbar-expand-lg navbar-light bg-light py-0 border-bottom sticky-top">
		<a class="navbar-brand" href="#">
			<img src="{% static 'imgs/logo.png' %}" class="rounded my-1">
		</a>
		<button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
		 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav ml-auto">
                	{% block nav %}
			<li class="nav-item m-sm-2">
				<a class="nav-link" href="index.html">Home</a>
			</li>
			<li class="nav-item m-sm-2">
				<a class="nav-link" href="#">About</a>
			</li>
			<li class="nav-item  m-sm-2">
				<a class="nav-link" href="#">HowTo</a>
			</li>
			<li class="nav-item">
				<a href="http://www.gigsync.in/#signup-tab"><button class="btn btn-outline-gspurple my-2" type="submit">Register</button></a>
	                </li>
                	{% endblock %}
			</ul>
			<!--<form class="form-inline my-2 my-lg-0">
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
					
				</form>-->
		</div>
	</header>
	<!-- END OF NAVBAR-->


    {% block main %}{% endblock %}


	<!--OPTIONAL GRADIENT-->
	<!--END OF OPTIONAL GRADIENT-->
		<!--FOOTER-->
	<div id="footer">

	</div>
	<!--END OF FOOTER-->
	<!-- Optional JavaScript -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
	 crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block custom_js %}{% endblock %}
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
     crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>

</body>

</html>

gigsyncevents/web/templates/web/date.html
{% extends "web/base.html" %}

{% block title %}GigSync Events|Home{% endblock %}

{% block nav %}
<li class="nav-item active m-sm-2">
        <a class="nav-link" href="index.html">Home</a>
    </li>
    <li class="nav-item m-sm-2">
        <a class="nav-link" href="#">About</a>
    </li>
    <li class="nav-item  m-sm-2">
        <a class="nav-link" href="#">HowTo</a>
    </li>
    <li class="nav-item">
        <a href="http://www.gigsync.in/#signup-tab"><button class="btn btn-outline-gspurple my-2" type="submit">Register</button></a>
    </li>
{% endblock %}

{% block main %}
    <div id="datespace" class="touch-scroll-list d-flex flex-row justify-content-md-center justify-content-start">
		<span class="date-pill lead border"><a href="{% url 'web:home' %}">All</a></span>
		<span class="date-pill lead border"><a href="{% url 'web:today' %}">Today</a></span>
		<span class="date-pill lead border"><a href="{% url 'web:tomorrow' %}">Tomorrow</a></span>
		<span class="date-pill lead border">Date<i class="far fa-calendar-alt ml-1" id="date-logo"></i></span>
    </div>
    <div class="container d-flex justify-content-center"><!--
        <div class="date-pill lead border">
            <div class="dropdown dropright">
                <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Filter
                </div>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    {% for city in cities %}
                    <a class="dropdown-item" href="{% url 'web:filter'%}">{{ city }}</a>
                    {% empty %}
                    Sorry! no cities found.
                    {% endfor %}
                </div>
            </div>
        </div>-->
        <button type="button" class="btn btn-outline-primary" id="filters">Filters</button>
    </div>
        <div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">Filters</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    <div class="modal-body d-flex justify-content-around">
                        <div class="d-flex flex-column">
                            <p class="lead">City</p>
                            <ul>
                                {% for city in cities %}
                                <input type="radio" name="city" value="{{ city }}"> {{ city }}<br>
                                {% empty %}
                                Sorry! No filters for city available.
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="d-flex flex-column">
                            <p class="lead">Genres</p>
                            <ul>
                                {% for genre in genres %}
                                <input type="checkbox" name="genre" value="{{ genre }}"> {{ genre }}<br>
                                {% empty %}
                                Sorry! No filters for genres available.
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="apply">Apply Filter</button>
                    </div>
                    </div>
                </div>
            </div>
    <div class="container">
            <p class="text-right">Showing {{ gigs|length }} results</p>
    </div>
	<div id="datepicker-conatiner" class="d-flex justify-content-center"><div id="datepicker"></div></div>
    <div class="container">
        <div class="event-area d-flex flex-column mr-0">

            {% for gig in gigs %}
            {% if forloop.first or forloop.counter0|divisibleby:"3" %}
            <div class="d-flex flex-row justify-content-around my-3 mr-0 p-2 event-cards-row">
            {% endif %}
                <div class="event-container">
                    <div class="card">
                        <a href="{% url 'web:event' gig.event_id %}"><img src="{{gig.cover_link}}" alt="" class="card-img-top"></a>
                        <div class="d-flex card-body flex-row p-0 m-0 event-info">
                            <div class="d-flex flex-column date-focus justify-content-center col-2 border-right m-1 p-1">
                                <div class="event-month text-center">{{ gig.start_date|date:"N" }}</div>
                                <div class="event-date text-center">{{ gig.start_date|date:"jS" }}</div>
                            </div>
                            <div class="d-flex flex-column justify-content-around event-title col-10 p-1">
                                <div class="event-name text-center">
                                    <a href="{% url 'web:event' gig.event_id %}">{{ gig.name }}</a>
                                </div>
                                <div class="event-venue text-center">{{ gig.venue }}</div>
                            </div>
                        </div>
                    </div>
                </div>

            {% if forloop.last or forloop.counter|divisibleby:"3" %}
            </div>   
            {% endif %}
            {% empty %}
                <p class="lead text-center">Sorry! No events on this day</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block custom_js %}
<script>
        function convertToSlug(Text)
        {
            return Text
                .toLowerCase()
                .replace(/ /g,'-')
                .replace(/[^\w-]+/g,'')
                ;
        }
        function getMonthNo(monthString){
            switch(monthString){
                case 'Jan': return '01';
                case 'Feb': return '02';
                case 'Mar': return '03';
                case 'Apr': return '04';
                case 'May': return '05';
                case 'Jun': return '06';
                case 'Jul': return '07';
                case 'Aug': return '08';
                case 'Sep': return '09';
                case 'Oct': return '10';
                case 'Nov': return '11';
                case 'Dec': return '12';
            }
        }

        function getFormattedDate(dateString){
            console.log('date_string: ' + dateString);
            monthString = dateString.slice(4,7);
            monthNo = getMonthNo(monthString);
            dayNo = dateString.slice(8, 10);
            yearNo = dateString.slice(11, 15);
            formattedDate = yearNo + '/' + monthNo + '/' + dayNo + '/';
            console.log('year: ' + yearNo);
            console.log('day:' + dayNo);
            console.log('month: ' + monthNo);
            return formattedDate;
        }

        $(document).ready(function(){
           $("#datepicker").datepicker({
               autoclose: true,
               format: "YYYY/MM/DD",
               todayHighlight: true, 
               startDate: new Date(),
               title: "Pick a Date",
           })
           .on('changeDate', function(){
               var date = $("#datepicker").datepicker("getDate");
               var date_obj = new Date(date.toString());
               //var date = Date.parse(date);
               console.log(typeof date_obj);
               console.log(typeof "df");
               console.log(window.location.protocol)
               console.log(window.location.host)
               console.log(window.location.pathname)
               redirect_url = window.location.protocol + '//' + window.location.host + '/date/' + getFormattedDate(date.toString())
               console.log(redirect_url)
               window.location = redirect_url
               $("#datepicker").hide();
           });
           $("#datepicker").hide();
           $("#date-logo").click(function(){
               $("#datepicker").toggle();
           });
           $("#filters").click(function(){
            $("#filterModal").modal('show');
       });
       console.log({{ day|stringformat:"02d" }});
       /*$(".city-item").click(function(){
           var city = convertToSlug($(this).text());
           redirect_url = window.location.protocol + '//' + window.location.host + '/date/{{ year }}/{{ month|stringformat:"02d" }}/{{ day|stringformat:"02d" }}/filter?city=' + city;
           window.location = redirect_url;
           console.log(city)
       });*/
       $('#apply').click(function(){
        var radios = document.getElementsByName('city');
        var checks = document.getElementsByName('genre');
        var city = '', genres = [];
        for (var i = 0, length = radios.length; i < length; i++)
        {
            if (radios[i].checked)
            {
            // do whatever you want with the checked radio
            city = radios[i].value;
            console.log(city);
            city = convertToSlug(city);
            // only one radio can be logically checked, don't check the rest
            break;
            }
        }
        for(var i = 0, length = checks.length; i < length; i++){
            if(checks[i].checked){
                var genre = checks[i].value;
                console.log(genre);
                genre = convertToSlug(genre);
                genres.push(genre);
            }
        }
        var params = '?';
        var params_city = 'city=';
        var params_genres = 'genres=';
        if(city != ''){
            params_city += city;
        }
        if(genres !== []){
            console.log(genres);
            for(var i = 0; i < genres.length; i++){
                params_genres += genres[i] + ',';
            }
        }

        if(params_city === 'city=' && params_genres === 'genres='){
            //$('#filterModal').modal('hide');
            alert('Please select filters');
        }
        else{
            if(params_city === 'city=' && params_genres !== 'genres='){
                params += params_genres;
            }
            else if(params_city !== 'city=' && params_genres === 'genres='){
                params += params_city;
            }
            else if(params_city !== 'city=' && params_genres !== 'genres='){
                params += params_city + '&' + params_genres;
            }
            console.log(params);
            //alert(params);
            redirect_url = window.location.protocol + '//' + window.location.host + '/date/{{ year }}/{{ month|stringformat:"02d" }}/{{ day|stringformat:"02d" }}/filter' + params;
            window.location = redirect_url;
        }

   });
    
    $('#filterModal').on('hidden.bs.modal', function () {
        var radios = document.getElementsByName('city');
        var checks = document.getElementsByName('genre');
        for(var i = 0; i < radios.length; i++){
            if(radios[i].checked){
                radios[i].checked = false;
                break;
            }
        }
        for(var i = 0; i < checks.length; i++){
            if(checks[i].checked){
                checks[i].checked = false;
            }
        }
    });
        });
    </script>
{% endblock %}

gigsyncevents/web/templates/web/howto.html
{% extends "web/base.html" %}
{% block title %}GigSync Events|About{% endblock %}

{% block nav %}
<li class="nav-item m-sm-2">
        <a class="nav-link" href="{% url 'web:home' %}">Home</a>
    </li>
    <li class="nav-item m-sm-2">
        <a class="nav-link" href="{% url 'web:about' %}">About</a>
    </li>
    <li class="nav-item active m-sm-2">
        <a class="nav-link" href="#">HowTo</a>
    </li>
    <li class="nav-item">
        <a href="http://www.gigsync.in/#signup-tab"><button class="btn btn-outline-gspurple my-2" type="submit">Register</button></a>
    </li>
{% endblock %}

{% block main %}
<div class="container my-5">
    <div class="d-flex flex-column justify-content-center">
        <p class="lead text-center">How To</p>
        <p class="text-center">How to text.</p>
    </div>
</div>
{% endblock %}

gigsyncevents/web/templates/web/index.html
{% extends "web/base.html" %}

{% block title %}GigSync Events|Home{% endblock %}

{% block nav %}
<li class="nav-item active m-sm-2">
        <a class="nav-link" href="index.html">Home</a>
    </li>
    <li class="nav-item m-sm-2">
        <a class="nav-link" href="{% url 'web:about' %}">About</a>
    </li>
    <li class="nav-item  m-sm-2">
        <a class="nav-link" href="{% url 'web:howto' %}">HowTo</a>
    </li>
    <li class="nav-item">
        <a href="http://www.gigsync.in/#signup-tab"><button class="btn btn-outline-gspurple my-2" type="submit">Register</button></a>
    </li>
{% endblock %}

{% block main %}
    <div id="datespace" class="touch-scroll-list d-flex flex-row justify-content-md-center justify-content-start">
        <span class="date-pill lead border"><a href="{% url 'web:home' %}">All</a></span>
		<span class="date-pill lead border"><a href="{% url 'web:today' %}">Today</a></span>
		<span class="date-pill lead border"><a href="{% url 'web:tomorrow' %}">Tomorrow</span></a>
        <span class="date-pill lead border">Date<i class="far fa-calendar-alt ml-1" id="date-logo"></i></span>
    </div>
    <div class="container d-flex justify-content-center"><!--
        <div class="date-pill lead border">
            <div class="dropdown dropright">
                <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Filter
                </div>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    {% for city in cities %}
                    <a class="dropdown-item" href="{% url 'web:filter'%}">{{ city }}</a>
                    {% empty %}
                    Sorry! no cities found.
                    {% endfor %}
                </div>
            </div>
        </div>-->
        <button type="button" class="btn btn-outline-primary" id="filters">Filters</button>
    </div>
    <div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Filters</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <div class="modal-body d-flex justify-content-around">
                <div class="d-flex flex-column">
                    <p class="lead">City</p>
                    <ul>
                        {% for city in cities %}
                        <input type="radio" name="city" value="{{ city }}"> {{ city }}<br>
                        {% empty %}
                        Sorry! No filters for city available.
                        {% endfor %}
                    </ul>
                </div>
                <div class="d-flex flex-column">
                    <p class="lead">Genres</p>
                    <ul>
                        {% for genre in genres %}
                        <input type="checkbox" name="genre" value="{{ genre }}"> {{ genre }}<br>
                        {% empty %}
                        Sorry! No filters for genres available.
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="apply">Apply Filters</button>
            </div>
            </div>
        </div>
    </div>
    <div class="container">
        <p class="text-right">Showing {{ gigs|length }} results</p>
    </div>
	<div id="datepicker-conatiner" class="d-flex justify-content-center"><div id="datepicker"></div></div>
    <div class="container">
        <div class="event-area d-flex flex-column mr-0">

            {% for gig in gigs %}
            {% if forloop.first or forloop.counter0|divisibleby:"3" %}
            <div class="d-flex flex-row justify-content-around my-3 mr-0 p-2 event-cards-row">
            {% endif %}
                <div class="event-container">
                    <div class="card">
                        <a href="{% url 'web:event' gig.event_id %}"><img src="{{gig.cover_link}}" alt="" class="card-img-top"></a>
                        <div class="d-flex card-body flex-row p-0 m-0 event-info">
                            <div class="d-flex flex-column date-focus justify-content-center col-2 border-right m-1 p-1">
                                <div class="event-month text-center">{{ gig.start_date|date:"N" }}</div>
                                <div class="event-date text-center">{{ gig.start_date|date:"jS" }}</div>
                            </div>
                            <div class="d-flex flex-column justify-content-around event-title col-10 p-1">
                                <div class="event-name text-center">
                                    <a href="{% url 'web:event' gig.event_id %}">{{ gig.name }}</a>
                                </div>
                                <div class="event-venue text-center">{{ gig.venue }}</div>
                            </div>
                        </div>
                    </div>
                </div>

            {% if forloop.last or forloop.counter|divisibleby:"3" %}
            </div>   
            {% endif %}
            {% empty %}
                <p class="lead text-center">Sorry! No events</p>
            {% endfor %}
        </div>
    </div>

    
{% endblock %}

{% block custom_js %}
<script>
        function convertToSlug(Text)
        {
            return Text
                .toLowerCase()
                .replace(/ /g,'-')
                .replace(/[^\w-]+/g,'')
                ;
        }
        function getMonthNo(monthString){
            switch(monthString){
                case 'Jan': return '01';
                case 'Feb': return '02';
                case 'Mar': return '03';
                case 'Apr': return '04';
                case 'May': return '05';
                case 'Jun': return '06';
                case 'Jul': return '07';
                case 'Aug': return '08';
                case 'Sep': return '09';
                case 'Oct': return '10';
                case 'Nov': return '11';
                case 'Dec': return '12';
            }
        }

        function getFormattedDate(dateString){
            console.log('date_string: ' + dateString);
            monthString = dateString.slice(4,7);
            monthNo = getMonthNo(monthString);
            dayNo = dateString.slice(8, 10);
            yearNo = dateString.slice(11, 15);
            formattedDate = yearNo + '/' + monthNo + '/' + dayNo + '/';
            console.log('year: ' + yearNo);
            console.log('day:' + dayNo);
            console.log('month: ' + monthNo);
            return formattedDate;
        }

        $(document).ready(function(){
           $("#datepicker").datepicker({
               autoclose: true,
               format: "YYYY/MM/DD",
               todayHighlight: true, 
               startDate: new Date(),
               title: "Pick a Date",
           })
           .on('changeDate', function(){
               var date = $("#datepicker").datepicker("getDate");
               var date_obj = new Date(date.toString());
               //var date = Date.parse(date);
               console.log(typeof date_obj);
               console.log(typeof "df")
               //redirect_url = 'localhost:8000/date/' + getFormattedDate(date.toString());
               console.log(window.location.protocol)
               console.log(window.location.host)
               console.log(window.location.pathname)
               redirect_url = window.location.protocol + '//' + window.location.host + '/date/' + getFormattedDate(date.toString())
               console.log(redirect_url)
               window.location = redirect_url
               $("#datepicker").hide();
            });
            $("#datepicker").hide();
            $("#date-logo").click(function(){
               $("#datepicker").toggle();
            });
            $("#filters").click(function(){
                $("#filterModal").modal('show');
            });
           /*$(".city-item").click(function(){
               var city = convertToSlug($(this).text());
               redirect_url = window.location.protocol + '//' + window.location.host + '/filter?city=' + city;
               window.location = redirect_url;
               console.log(city)
           });*/
           $('#apply').click(function(){
                var radios = document.getElementsByName('city');
                var checks = document.getElementsByName('genre');
                var city = '', genres = [];
                for (var i = 0, length = radios.length; i < length; i++)
                {
                    if (radios[i].checked)
                    {
                    // do whatever you want with the checked radio
                    city = radios[i].value;
                    console.log(city);
                    city = convertToSlug(city);
                    // only one radio can be logically checked, don't check the rest
                    break;
                    }
                }
                for(var i = 0, length = checks.length; i < length; i++){
                    if(checks[i].checked){
                        var genre = checks[i].value;
                        console.log(genre);
                        genre = convertToSlug(genre);
                        genres.push(genre);
                    }
                }
                var params = '?';
                var params_city = 'city=';
                var params_genres = 'genres=';
                if(city != ''){
                    params_city += city;
                }
                if(genres !== []){
                    console.log(genres);
                    for(var i = 0; i < genres.length; i++){
                        params_genres += genres[i] + ',';
                    }
                }

                if(params_city === 'city=' && params_genres === 'genres='){
                    //$('#filterModal').modal('hide');
                    alert('Please select filters');
                }
                else{
                    if(params_city === 'city=' && params_genres !== 'genres='){
                        params += params_genres;
                    }
                    else if(params_city !== 'city=' && params_genres === 'genres='){
                        params += params_city;
                    }
                    else if(params_city !== 'city=' && params_genres !== 'genres='){
                        params += params_city + '&' + params_genres;
                    }
                    console.log(params);
                    //alert(params);
                    redirect_url = window.location.protocol + '//' + window.location.host + '/filter' + params;
                    window.location = redirect_url;
                }

           });
            
            $('#filterModal').on('hidden.bs.modal', function () {
                var radios = document.getElementsByName('city');
                var checks = document.getElementsByName('genre');
                for(var i = 0; i < radios.length; i++){
                    if(radios[i].checked){
                        radios[i].checked = false;
                        break;
                    }
                }
                for(var i = 0; i < checks.length; i++){
                    if(checks[i].checked){
                        checks[i].checked = false;
                    }
                }
            });
        });
    </script>
{% endblock %}